# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import tweets_app.validate


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=140, validators=[tweets_app.validate.validate_content]),
        ),
    ]
