# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-01 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_app', '0002_auto_20180923_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
